package com.xuanhai.models;
// Generated Oct 11, 2016 5:24:08 PM by Hibernate Tools 4.3.1

/**
 * Ban generated by hbm2java
 */
public class Ban implements java.io.Serializable {

    private int banId;
    private String soBan;
    private String trangThai;

    public Ban() {
    }

    public Ban(int banId) {
        this.banId = banId;
    }

    public Ban(int banId, String soBan, String trangThai) {
        this.banId = banId;
        this.soBan = soBan;
        this.trangThai = trangThai;
    }

    public int getBanId() {
        return this.banId;
    }

    public void setBanId(int banId) {
        this.banId = banId;
    }

    public String getSoBan() {
        return this.soBan;
    }

    public void setSoBan(String soBan) {
        this.soBan = soBan;
    }

    public String getTrangThai() {
        return this.trangThai;
    }

    public void setTrangThai(String trangThai) {
        this.trangThai = trangThai;
    }

}
