package com.xuanhai.models;
// Generated Oct 11, 2016 5:24:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ChiTietHoaDon generated by hbm2java
 */
public class ChiTietHoaDon  implements java.io.Serializable {


     private int chiTietHoaDonId;
     private int hoaDonId;
     private int sanPhamId;
     private BigDecimal donGia;

    public ChiTietHoaDon() {
    }

	
    public ChiTietHoaDon(int chiTietHoaDonId, int hoaDonId, int sanPhamId) {
        this.chiTietHoaDonId = chiTietHoaDonId;
        this.hoaDonId = hoaDonId;
        this.sanPhamId = sanPhamId;
    }
    public ChiTietHoaDon(int chiTietHoaDonId, int hoaDonId, int sanPhamId, BigDecimal donGia) {
       this.chiTietHoaDonId = chiTietHoaDonId;
       this.hoaDonId = hoaDonId;
       this.sanPhamId = sanPhamId;
       this.donGia = donGia;
    }
   
    public int getChiTietHoaDonId() {
        return this.chiTietHoaDonId;
    }
    
    public void setChiTietHoaDonId(int chiTietHoaDonId) {
        this.chiTietHoaDonId = chiTietHoaDonId;
    }
    public int getHoaDonId() {
        return this.hoaDonId;
    }
    
    public void setHoaDonId(int hoaDonId) {
        this.hoaDonId = hoaDonId;
    }
    public int getSanPhamId() {
        return this.sanPhamId;
    }
    
    public void setSanPhamId(int sanPhamId) {
        this.sanPhamId = sanPhamId;
    }
    public BigDecimal getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(BigDecimal donGia) {
        this.donGia = donGia;
    }




}


