package com.xuanhai.models;
// Generated Oct 11, 2016 5:24:08 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DatBan generated by hbm2java
 */
public class DatBan  implements java.io.Serializable {


     private int datBanId;
     private int banId;
     private int sanPhamId;
     private Date thoiGian;
     private Integer soLuong;

    public DatBan() {
    }

	
    public DatBan(int datBanId, int banId, int sanPhamId) {
        this.datBanId = datBanId;
        this.banId = banId;
        this.sanPhamId = sanPhamId;
    }
    public DatBan(int datBanId, int banId, int sanPhamId, Date thoiGian, Integer soLuong) {
       this.datBanId = datBanId;
       this.banId = banId;
       this.sanPhamId = sanPhamId;
       this.thoiGian = thoiGian;
       this.soLuong = soLuong;
    }
   
    public int getDatBanId() {
        return this.datBanId;
    }
    
    public void setDatBanId(int datBanId) {
        this.datBanId = datBanId;
    }
    public int getBanId() {
        return this.banId;
    }
    
    public void setBanId(int banId) {
        this.banId = banId;
    }
    public int getSanPhamId() {
        return this.sanPhamId;
    }
    
    public void setSanPhamId(int sanPhamId) {
        this.sanPhamId = sanPhamId;
    }
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }




}


