package com.xuanhai.models;
// Generated Oct 11, 2016 5:24:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * DatBan generated by hbm2java
 */
@Entity
@Table(name = "dat_ban", catalog = "coffee_shop")
public class DatBan implements java.io.Serializable {

    private int datBanId;
    private Integer soLuong;
    private SanPham sanPham;
    private Ban ban;

    private Date createDate;
    private Date updateDate;

    public DatBan() {
    }

    public DatBan(Integer soLuong, SanPham sanPham, Ban ban) {
        this.soLuong = soLuong;
        this.sanPham = sanPham;
        this.ban = ban;
        this.createDate = new Date();
        this.updateDate = new Date();
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "dat_ban_id", unique = true, nullable = false)
    public int getDatBanId() {
        return datBanId;
    }

    public void setDatBanId(int datBanId) {
        this.datBanId = datBanId;
    }

    @Column(name = "so_luong")
    public Integer getSoLuong() {
        return soLuong;
    }

    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "san_pham_id", nullable = false)
    public SanPham getSanPham() {
        return sanPham;
    }

    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ban_id", nullable = false)
    public Ban getBan() {
        return ban;
    }

    public void setBan(Ban ban) {
        this.ban = ban;
    }

    @Column(name = "create_date")
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Column(name = "update_date")
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

}
