package com.xuanhai.models;
// Generated Oct 11, 2016 5:24:08 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * HoaDon generated by hbm2java
 */
public class HoaDon  implements java.io.Serializable {


     private int hoaDonId;
     private int banId;
     private int nhanVienId;
     private Date ngayHoaDon;
     private BigDecimal tongTriGia;

    public HoaDon() {
    }

	
    public HoaDon(int hoaDonId, int banId, int nhanVienId) {
        this.hoaDonId = hoaDonId;
        this.banId = banId;
        this.nhanVienId = nhanVienId;
    }
    public HoaDon(int hoaDonId, int banId, int nhanVienId, Date ngayHoaDon, BigDecimal tongTriGia) {
       this.hoaDonId = hoaDonId;
       this.banId = banId;
       this.nhanVienId = nhanVienId;
       this.ngayHoaDon = ngayHoaDon;
       this.tongTriGia = tongTriGia;
    }
   
    public int getHoaDonId() {
        return this.hoaDonId;
    }
    
    public void setHoaDonId(int hoaDonId) {
        this.hoaDonId = hoaDonId;
    }
    public int getBanId() {
        return this.banId;
    }
    
    public void setBanId(int banId) {
        this.banId = banId;
    }
    public int getNhanVienId() {
        return this.nhanVienId;
    }
    
    public void setNhanVienId(int nhanVienId) {
        this.nhanVienId = nhanVienId;
    }
    public Date getNgayHoaDon() {
        return this.ngayHoaDon;
    }
    
    public void setNgayHoaDon(Date ngayHoaDon) {
        this.ngayHoaDon = ngayHoaDon;
    }
    public BigDecimal getTongTriGia() {
        return this.tongTriGia;
    }
    
    public void setTongTriGia(BigDecimal tongTriGia) {
        this.tongTriGia = tongTriGia;
    }




}


