package com.xuanhai.models;
// Generated Oct 11, 2016 5:24:08 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * HoaDon generated by hbm2java
 */
@Entity
@Table(name = "hoa_don", catalog = "coffee_shop")
public class HoaDon implements java.io.Serializable {

    private int hoaDonId;
    private Date ngayHoaDon;
    private BigDecimal tongTriGia;
    private int giamGia;
    private Ban ban;
    private NhanVien nhanVien;

    public HoaDon() {
    }

    public HoaDon(BigDecimal tongTriGia, int giamGia, Ban ban, NhanVien nhanVien) {
        this.ngayHoaDon = new java.util.Date();
        this.tongTriGia = tongTriGia;
        this.giamGia = giamGia;
        this.ban = ban;
        this.nhanVien = nhanVien;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "hoa_don_id", unique = true, nullable = false)
    public int getHoaDonId() {
        return this.hoaDonId;
    }

    public void setHoaDonId(int hoaDonId) {
        this.hoaDonId = hoaDonId;
    }

    @Column(name = "ngay_hoa_don")
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    public Date getNgayHoaDon() {
        return ngayHoaDon;
    }

    public void setNgayHoaDon(Date ngayHoaDon) {
        this.ngayHoaDon = ngayHoaDon;
    }

    @Column(name = "tong_tri_gia", scale = 2)
    public BigDecimal getTongTriGia() {
        return tongTriGia;
    }

    public void setTongTriGia(BigDecimal tongTriGia) {
        this.tongTriGia = tongTriGia;
    }

    @Column(name = "giam_gia")
    public int getGiamGia() {
        return giamGia;
    }

    public void setGiamGia(int giamGia) {
        this.giamGia = giamGia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "nhan_vien_id", nullable = false)
    public NhanVien getNhanVien() {
        return nhanVien;
    }

    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ban_id", nullable = false)
    public Ban getBan() {
        return ban;
    }

    public void setBan(Ban ban) {
        this.ban = ban;
    }

}
