package com.xuanhai.models;
// Generated Oct 11, 2016 5:24:08 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiSanPham generated by hbm2java
 */
@Entity
@Table(name = "loai_san_pham", catalog = "coffee_shop")
public class LoaiSanPham implements java.io.Serializable {

    private Integer loaiSanPhamId;
    private String tenLoaiSanPham;

    private Set<SanPham> sanPhams = new HashSet<>();

    public LoaiSanPham() {
    }

    public LoaiSanPham(String tenLoaiSanPham) {
        this.tenLoaiSanPham = tenLoaiSanPham;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "loai_san_pham_id", unique = true, nullable = false)
    public Integer getLoaiSanPhamId() {
        return loaiSanPhamId;
    }

    public void setLoaiSanPhamId(Integer loaiSanPhamId) {
        this.loaiSanPhamId = loaiSanPhamId;
    }

    @Column(name = "ten_loai_san_pham", unique = true, nullable = false)
    public String getTenLoaiSanPham() {
        return tenLoaiSanPham;
    }

    public void setTenLoaiSanPham(String tenLoaiSanPham) {
        this.tenLoaiSanPham = tenLoaiSanPham;
    }

    @OneToMany(cascade = CascadeType.REMOVE, fetch = FetchType.LAZY, mappedBy = "loaiSanPham")
    public Set<SanPham> getSanPhams() {
        return sanPhams;
    }

    public void setSanPhams(Set<SanPham> sanPhams) {
        this.sanPhams = sanPhams;
    }

    @Override
    public String toString() {
        return tenLoaiSanPham;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 71 * hash + Objects.hashCode(this.loaiSanPhamId);
        hash = 71 * hash + Objects.hashCode(this.tenLoaiSanPham);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LoaiSanPham other = (LoaiSanPham) obj;
        if (!Objects.equals(this.tenLoaiSanPham, other.tenLoaiSanPham)) {
            return false;
        }
        if (!Objects.equals(this.loaiSanPhamId, other.loaiSanPhamId)) {
            return false;
        }
        return true;
    }

    
    
}
