package com.xuanhai.models;
// Generated Oct 11, 2016 5:24:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "nhan_vien", catalog = "coffee_shop")
public class NhanVien implements java.io.Serializable {

    private int nhanVienId;
    private String hoTen;
    private Date ngaySinh;
    private Date ngayVaoLam;
    private String username;
    private String password;

    public NhanVien() {
    }

    public NhanVien(String hoTen, Date ngaySinh, Date ngayVaoLam, String username, String password) {
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.ngayVaoLam = ngayVaoLam;
        this.username = username;
        this.password = password;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "nhan_vien_id", unique = true, nullable = false)
    public int getNhanVienId() {
        return this.nhanVienId;
    }

    public void setNhanVienId(int nhanVienId) {
        this.nhanVienId = nhanVienId;
    }

    @Column(name = "ho_ten", nullable = false)
    public String getHoTen() {
        return this.hoTen;
    }

    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ngay_sinh", nullable = false)
    public Date getNgaySinh() {
        return this.ngaySinh;
    }

    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ngay_vao_lam", nullable = false)
    public Date getNgayVaoLam() {
        return this.ngayVaoLam;
    }

    public void setNgayVaoLam(Date ngayVaoLam) {
        this.ngayVaoLam = ngayVaoLam;
    }

    @Column(name = "username", nullable = false)
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "password", nullable = false)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return hoTen;
    }

}
