package com.xuanhai.models;
// Generated Oct 11, 2016 5:24:08 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SanPham generated by hbm2java
 */
@Entity
@Table(name = "san_pham", catalog = "coffee_shop")
public class SanPham implements java.io.Serializable {

    private int sanPhamId;
    private String tenSanPham;
    private BigDecimal donGia;
    private Integer soLuong;
    private LoaiSanPham loaiSanPham;

    public SanPham() {
    }

    public SanPham(String tenSanPham, BigDecimal donGia, Integer soLuong, LoaiSanPham loaiSanPham) {
        this.tenSanPham = tenSanPham;
        this.donGia = donGia;
        this.soLuong = soLuong;
        this.loaiSanPham = loaiSanPham;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "san_pham_id", unique = true, nullable = false)
    public int getSanPhamId() {
        return this.sanPhamId;
    }

    public void setSanPhamId(int sanPhamId) {
        this.sanPhamId = sanPhamId;
    }

    @Column(name = "ten_san_pham", unique = true, nullable = false)
    public String getTenSanPham() {
        return this.tenSanPham;
    }

    public void setTenSanPham(String tenSanPham) {
        this.tenSanPham = tenSanPham;
    }

    @Column(name = "don_gia", scale = 2)
    public BigDecimal getDonGia() {
        return this.donGia;
    }

    public void setDonGia(BigDecimal donGia) {
        this.donGia = donGia;
    }

    @Column(name = "so_luong")
    public Integer getSoLuong() {
        return this.soLuong;
    }

    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "loai_san_pham_id", nullable = false)
    public LoaiSanPham getLoaiSanPham() {
        return loaiSanPham;
    }

    public void setLoaiSanPham(LoaiSanPham loaiSanPham) {
        this.loaiSanPham = loaiSanPham;
    }

    @Override
    public String toString() {
        return tenSanPham;
    }

}
